<%
  # http://mislav.uniqpath.com/rails/branching-the-database-along-with-your-code/
  branch = `git symbolic-ref HEAD 2>/dev/null`.chomp.sub('refs/heads/', '')
  use_database = `git config branch.#{branch}.database`.chomp
  suffix = if use_database == 'true'
    branch
  elsif use_database.present?
    use_database
  else
    "master"
  end
%>

defaults: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 25
  host: localhost

development:
  <<: *defaults
  database: wwsv_development_<%= suffix %>

production:
  <<: *defaults
  database: wwsv_development_<%= suffix %>

test:
  <<: *defaults
  database: wwsv_test_<%= suffix %>
