development:
  access_key_id:     AKIAJ2FJVCFJW3RZRUUQ
  secret_access_key: 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
  buckets:
    tailor_made_requests: dev.sublimevideo.tailor-made-requests

test:
  access_key_id:     AKIAJ2FJVCFJW3RZRUUQ
  secret_access_key: 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
  buckets:
    tailor_made_requests: dev.sublimevideo.tailor-made-requests

staging:
  access_key_id:     AKIAJ2FJVCFJW3RZRUUQ
  secret_access_key: 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
  buckets:
    tailor_made_requests: staging.sublimevideo.tailor-made-requests

production:
  access_key_id:     env_var
  secret_access_key: env_var
  buckets:
    tailor_made_requests: sublimevideo.tailor-made-requests
